### ISSUE TITLE
also i'm also trying to reverse engineer how did you get mapping json

### ISSUE THREAD

**Issue by techsin** [Fugiman/agario-assist#2]
What i am doing is going over all minified code and guess what their name should be based on their functionality but 
there are dozens of variables which im very lost about.

**Comment by Fugiman** [comment]
https://github.com/Fugiman/agario-assist/blob/master/reverse_engineering/game.golden.js is a copy of the unminified source code I grabbed when the dev of agario accidentally uploaded it, and greatly helps in figuring out what the code does.

**Comment by Fugiman** [comment]
Answered question in README via e00bde420c1443cf5784b51bbf94c23dbe9ce967
