### ISSUE TITLE
Agario not loading when using extension

### ISSUE THREAD

**Issue by daredevil28** [Fugiman/agario-assist#3]
When i openend the extensions, agario stopped working.
JavaScript console says this: "
GET http://static.addtoany.com/menu/page.js net::ERR_BLOCKED_BY_CLIENT
(index):120 GET http://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js net::ERR_BLOCKED_BY_CLIENT
content.js:5 Iframe attached successfully"
and this : "Uncaught ReferenceError: Cell is not definedVM931:1201 overrideVM931:1225 rootVM931:1226 (anonymous function)injected.js:8 (anonymous function)injected.js:5 Ainjected.js:5 jinjected.js:5 (anonymous function)injected.js:5 V"

**Comment by rauppe31** [comment]
Same issue here

**Comment by Raphy** [comment]
the same for me

**Comment by Fugiman** [comment]
Should be fixed now, thanks!

**Comment by rauppe31** [comment]
@Fugiman When will the Google Chrome extension in the store be updated?

**Comment by Fugiman** [comment]
Oh sorry, I uploaded the new package last night, but never hit "publish" >_>

New version is uploaded now
